import streamlit as st
import os
import random
import json

class SaveConversation:
    def __init__(self, memory) -> None:
        self.memory = memory
        os.makedirs('./feedback/conversations/', exist_ok=True)

    def make_json(self, id):
        convo_list = []
        messages = self.memory.messages
        for i, msg in enumerate(messages):
            if (i % 2 != 0) and (i+1 < len(messages)):
                convo_list.append([msg, messages[i+1]])
            elif (i+1 == len(messages)):
                convo_list.append([msg])
        
        convo_json = []
        for convo in convo_list:
            convo_dict = {}
            if len(convo) == 2:
                convo_dict['AI'] = convo[0].content
                convo_dict['Human'] = convo[1].content
            else:
                convo_dict['AI'] = convo[0].content
                convo_dict['Human'] = ''
            convo_json.append(convo_dict)
        
        with open(f"./feedback/conversations/{id}.json", "w") as f:
            json.dump(convo_json, f)    

class FeedbackSurvey:
    def __init__(self, memory) -> None:
        self.memory = memory
        self.sc = SaveConversation(self.memory)

    def make_survey(self):
        os.makedirs('./feedback', exist_ok=True)
        id = f"{len(os.listdir('./feedback'))}_{random.randint(10_000, 20_000)}"
        with st.form('student_feedback'):
            st.write("## Feedback")
            st.write("### Ease of Use :notebook_with_decorative_cover:")
            likert1 = st.slider("1. I find the PT Tutor application easy to use.", min_value=1, max_value=5, value=3)
            likert2 = st.slider("2. I can easily navigate through the PT Tutor application.", min_value=1, max_value=5, value=3)
            likert3 = st.slider("3.	The features of the PT Tutor application are easy to understand.", min_value=1, max_value=5, value=3)
            st.write("### Usefulness of Quiz Questions :writing_hand:")
            likert4 = st.slider("4.	The quiz questions generated by PT Tutor are relevant to my study material.", min_value=1, max_value=5, value=3)
            likert5 = st.slider("5.	The quiz questions help me understand and remember the lecture content better.", min_value=1, max_value=5, value=3)
            likert6 = st.slider("6.	I find the quiz questions challenging but achievable.", min_value=1, max_value=5, value=3)
            st.write("### Impact in Study Habits :student:")
            likert7 = st.slider("7.	I spend more time studying because of the PT Tutor application.", min_value=1, max_value=5, value=3)
            likert8 = st.slider("8.	PT Tutor helps me study more effectively.", min_value=1, max_value=5, value=3)
            st.write("### Perceived Impact on Learning Outcomes :mortar_board:")
            likert9 = st.slider("9.	PT Tutor has improved my understanding of the course material.", min_value=1, max_value=5, value=3)
            likert10 = st.slider("10. PT Tutor helps me perform better in assessments/exams.", min_value=1, max_value=5, value=3)
            likert11 = st.slider("11. PT Tutor has improved my overall academic performance.", min_value=1, max_value=5, value=3)
            st.write("### Overall Satisfaction :trophy:")
            likert12 = st.slider("12. I am satisfied with the features and functionality of the PT Tutor application.", min_value=1, max_value=5, value=3)
            likert13 = st.slider("13. I would recommend the PT Tutor application to other students.", min_value=1, max_value=5, value=3)
            likert14 = st.slider("14. I will continue to use the PT Tutor application in the future.", min_value=1, max_value=5, value=3)
            fr = st.text_area("(Optional) Please give any general feedback you might have.")
        
            submitted = st.form_submit_button("Submit")
            if submitted:
                with open(f"./feedback/{id}_feedback.csv", "w") as f:
                    f.write(f"ID, Q1, Q2, Q3, Q4, Q5, Q6, Q7, Q8, Q9, Q10, Q11, Q12, Q13, Q14\n")
                    f.write(f"{id}, {likert1}, {likert2}, {likert3}, {likert4}, {likert5}, {likert6}, {likert7}, {likert8}, {likert9}, {likert10}, {likert11}, {likert12}, {likert13}, {likert14}, {fr}\n")
                self.sc.make_json(id)
